version: "3.8"

services:
  redis:
    container_name: tundra-redis
    image: redis:6.0.9-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  
  tundra:
    container_name: tundra-dns
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8053:8053/tcp # Change to listen on Tailscale IP
      - 53:53/udp
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data:/app

  tundra-portal:
    container_name: tundra-portal
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080/tcp # Change to listen on Tailscale IP
    depends_on:
      - tundra

    